-- Abscondata operational schema
-- This file is a reference only. The actual schema is managed through migrations.
-- See supabase/migrations/ for the authoritative table definitions.
--
-- Core tables (from migrations 001-002):
--   profiles, clients, tasks, exceptions, weekly_reports,
--   client_configs, task_source_data, task_events, send_logs,
--   task_logs, sops, files
--
-- Rebuild tables (from migration 004):
--   client_services, client_platforms, onboarding_submissions,
--   task_templates, imports
